<?php

module_load_include('inc', 'dl_course', 'inc/dl_course.functions');

/**
 * implementation of hook_node_load
 */

function dl_course_node_load($nodes, $types) {
  foreach($nodes as $node) {
    switch($node->type) {
      case 'article':
        if (isset($node->field_lessons['und'])) {  //set lessons order
          if (count($node->field_lessons['und']) > 0) {
            $query = db_select('field_data_field_order_number' , 'fon');
            $query->fields('fon', array('entity_id'));
            $query->innerJoin('field_data_field_lessons', 'fl', 'fl.field_lessons_target_id = fon.entity_id');
            $query->condition('fl.entity_id', $node->nid);
            $query->orderBy('fon.field_order_number_value');
            $results = $query->execute();
            
            $i = 0;
            foreach($results as $record) {
              $node->field_lessons['und'][$i]['target_id'] = $record->entity_id;
              $i++;
            }
          }
        }
        break;
    }
  }
}

/**
 * implementation of hook_node_view
 */

function dl_course_node_view($node, $view_mode, $langcode) {
  global $base_url;
  switch($node->type) {
    case 'article':
      $tax_parents = taxonomy_get_parents($node->field_category['und'][0]['tid']);
      $last_term = taxonomy_term_load($node->field_category['und'][0]['tid']);
      
      
      $breadcrumbs = array();
      $breadcrumbs[] = l('Главная', $base_url);

      foreach($tax_parents as $term) {
        $breadcrumbs[] = l($term->name, 'taxonomy/term/' . $term->tid);
      }
      
      $breadcrumbs[] = l($last_term->name, 'taxonomy/term/' . $last_term->tid);
      
      $breadcrumbs[] = $node->title;
      
      drupal_set_breadcrumb($breadcrumbs);
      break;
    case 'lesson':
      $query = db_select('field_data_field_lessons', 'fl');
      $query->innerJoin('node', 'n', 'n.nid = fl.entity_id');
      $query->innerJoin('field_data_field_category', 'fc', 'fc.entity_id = fl.entity_id');
      $query->fields('n', array('title', 'nid'));
      $query->fields('fc', array('field_category_tid'));
      $query->condition('fl.field_lessons_target_id', $node->nid);
      $query->range(0, 1);
      
      $course_data = $query->execute()->fetchAssoc();
      
      $tax_parents = taxonomy_get_parents($course_data['field_category_tid']);
      $last_term = taxonomy_term_load($course_data['field_category_tid']);
      
      
      $breadcrumbs = array();
      $breadcrumbs[] = l('Главная', $base_url);

      foreach($tax_parents as $term) {
        $breadcrumbs[] = l($term->name, 'taxonomy/term/' . $term->tid);
      }
      
      $breadcrumbs[] = l($last_term->name, 'taxonomy/term/' . $last_term->tid);
      
      $breadcrumbs[] = l($course_data['title'], 'node/' . $course_data['nid']);
      
      $breadcrumbs[] = $node->title;
      drupal_set_breadcrumb($breadcrumbs);
      break;
  }   
}


/**
 * implementation of hook_block_info
 */
 

function dl_course_block_info() {
  $blocks['course_navigate'] = array(
    'info' => t('Course navigation'), 
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * implementation of hook_block_view
 */
 
function dl_course_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'course_navigate':
      $block['subject'] = t('Course navigation');
      $block['content'] = _dl_course_get_course_navigation_block_content();
      break;
  }
  return $block;
}


/**
 * implementatin of hook_theme
 */
 
function dl_course_theme($existing, $type, $theme, $path) {
  return array(
    'course_navigation' => array(
      'file' => 'inc/dl_course.theme.inc',
    ), 
  );
}